version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-ts
    restart: "no"
    ports:
      - "6379:6379"
      - "8001:8001"
    command: ["redis-server", "--requirepass", "rorana123"]
    volumes:
      - redis_data:/data  # persistent storage

volumes:
  redis_data: